### PR TITLE
[Rename]: Leo ==> Nala :sob: 

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Renames Leo to Nala :sob: 

### TODO
- [ ] Rename LEO_UPDATE_ICONS_PAT to NALA_UPDATE_ICONS_PAT
- [ ] Add redirect from https://leo.bravesoftware.com/ to https://nala.bravesoftware.com/
- [ ] Move the repo to https://github.com/brave/nala
- [ ] Move https://github.com/brave/leo-sf-symbols/ to https://github.com/brave/nala-sf-symbols/

### Notes
- I've used `nala` instead of Leo for everything internal (i.e. class names, variables ect). 
- CSS variables now use a `--nl-` prefix instead of a `--leo-` prefix
- WebComponents use an `nl-` prefix instead of a `leo-` prefix (i.e. `nl-button`)

### CODE REVIEW

**Comment by sangwoo108** [comment]
The branch name is the saddest one that I've ever seen 😂

**Comment by AlanBreck** [comment]
Wondering if, even though an extra character, it would be better for grepping repos to use `nala` instead of `nl` for the prefix.

**Comment by fallaciousreasoning** [comment]
@AlanBreck happy to change it, but I'm not sure it'll be any different `-nl-` is going to be pretty unique :laughing: @petemill, what's your preference?

**Comment by fallaciousreasoning** [comment]
See https://github.com/brave/devops/issues/10511 for the Storybook redirect

**Comment by AlanBreck** [comment]
Wondering if we can get some other PRs merged prior to proceeding with this one.

**Comment by fallaciousreasoning** [comment]
**Note:** Change `nl` prefix to `nala`

**Comment by thypon** [comment]
> @AlanBreck happy to change it, but I'm not sure it'll be any different `-nl-` is going to be pretty unique 😆 @petemill, what's your preference?

NL stands for Netherlands, there is a `.nl` too. Not very unique

**Comment by fallaciousreasoning** [comment]
Closing this - it's so out of date it'll be easier to restart from scratch

**Pull request closed without merging**
