### PR TITLE
WIP: Add optional delay to alert center actions

### PR DESCRIPTION
**Pull request by AlanBreck**
https://github.com/user-attachments/assets/56c5bb1d-8966-4344-bba2-48c84413ba88

### CODE REVIEW

**Review by fallaciousreasoning — COMMENTED** [review]
Hey, so I think this is a great idea - I wonder if we can come up with a more generic approach that'd let us change buttons on the fly, rather than needing to hardcode support in the alert center.

That said, maybe this is the only thing we'd want to change?

**Comment by AlanBreck** [comment]
> Hey, so I think this is a great idea - I wonder if we can come up with a more generic approach that'd let us change buttons on the fly, rather than needing to hardcode support in the alert center.
> 
> 
> 
> That said, maybe this is the only thing we'd want to change?

I suppose we could just leverage the ability to pass a custom Alert component, and leave this behavior up to consuming apps.

**Comment by AlanBreck** [comment]
> a more generic approach that'd let us change buttons on the fly

Actually, mind fleshing this out a bit more?

**Comment by fallaciousreasoning** [comment]
I always struggle a bit with stuff like this in Svelte:

Something like https://github.com/brave/leo/pull/786 is what I was thinking. What are your thoughts?

**Comment by AlanBreck** [comment]
https://github.com/brave/leo/pull/789 is definitely a lot cleaner. I suppose that solution would still allow for updating the text, yes? The downside is that we couldn't have the ProgressRing. Unless we passed a custom Button component? Maybe we just don't support that and rely on text.

So the essential difference here is that the AlertCenter provides an API to imperatively update the alert, and the the consumer would own the logic for what constitutes an update, etc. Yes?

**Comment by fallaciousreasoning** [comment]
Yeah exactly :smile: We could even add in an optional prop for the progress, I guess?

**Comment by AlanBreck** [comment]
Closing in favor of https://github.com/brave/leo/pull/789

**Pull request closed without merging**
