### PR TITLE
fix: provided type for button onClick prop

### PR DESCRIPTION
**Pull request by brandedcow**
Need to update Button Props to resolve event type onClick for this issue:

https://github.com/brave/brave-browser/issues/36550

### CODE REVIEW

**Review by AlanBreck — CHANGES_REQUESTED** [review]
Thanks for contributing, @brandedcow!

Appears that `npm run check` fails, and I believe it's because you need to import the `MouseEventHandler` type from `svelte/elements` and use `MouseEventHandler<HTMLAnchorElement|HTMLButtonElement>` instead of `svelte.JSX.MouseEventHandler<HTMLButtonElement>`.

Additionally note the `HTMLAnchorElement|HTMLButtonElement` as this button component can be either a `<button>` element or an `<anchor>` element.

**Comment by fallaciousreasoning** [comment]
I'd be tempted to type it as an `MouseEvent` instead of anything fancier :smile:

**Comment by brandedcow** [comment]
Made the adjustments with the recommendation from @fallaciousreasoning. 👌

**Review by AlanBreck — APPROVED** [review]

**Comment by AlanBreck** [comment]
LGTM. Thank you, @brandedcow! 

Please wait for @fallaciousreasoning to review before merging.

**Review by fallaciousreasoning — APPROVED** [review]

**Comment by fallaciousreasoning** [comment]
@brandedcow would you mind setting up commit signing and rebasing?

https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

We can't merge unsigned commits in Brave org repos.

**Comment by fallaciousreasoning** [comment]
Nice work @brandedcow - running CI now

**Pull request merged**
