### PR TITLE
[Icons]: Update icons from Figma

### PR DESCRIPTION
**Pull request by kim0**
> @brave/leo@0.0.1 update-icons
> node ./src/scripts/update-icons.js

Ignoring icon default-false.svg because:
- has a raster image element
Ignoring icon glow-color.svg because:
- has a raster image element
Ignoring icon rainbow-color.svg because:
- has a raster image element
Ignoring icon bitcoin.com-color.svg because:
- has a raster image element
Ignoring icon daum-color.svg because:
- has a raster image element

### CODE REVIEW

**Comment by AlanBreck** [comment]
Are these PRs actually being opened by @kim0, or is this an action associated with his token? If the latter, can we change to a Leo bot, or something?

**Comment by fallaciousreasoning** [comment]
It's an action associated with his token :laughing:

**Review by fallaciousreasoning — APPROVED** [review]
LGTM

**Comment by kim0** [comment]
> Are these PRs actually being opened by @kim0, or is this an action associated with his token? If the latter, can we change to a Leo bot, or something?

I worked with Sam Brown to get those tokens regenerated and updated. They should no longer be attached to my account 🎉 Please test the two workflows, and if there's any permission errors, please contact #it-support to update the tokens. I believe the PRs will be owned by an account `brave-support-admin` bec they're consolidating tokens under that account name.

cc @AlanBreck @fallaciousreasoning

**Comment by AlanBreck** [comment]
Nice. Thank you, @kim0!

**Comment by fallaciousreasoning** [comment]
Woohoo thanks @kim0 !

**Pull request merged**
