### PR TITLE
Tokens

### PR DESCRIPTION
**Pull request by aguscruiz**

### CODE REVIEW

**Comment by fallaciousreasoning** [comment]
I think I'll need to update some of the components, but hopefully it'll do a build and we'll be able to see :smile: 

By the way, can you reset your local branch to where this one is? That way next time the update should be much smaller:

```
git fetch
git reset origin/tokens
```

**Review by fallaciousreasoning — APPROVED** [review]
LGTM

**Comment by aguscruiz** [comment]
> I think I'll need to update some of the components, but hopefully it'll do a build and we'll be able to see 😄
> 
> By the way, can you reset your local branch to where this one is? That way next time the update should be much smaller:
> 
> ```
> git fetch
> git reset origin/tokens --hard
> ```

Oh I thought I was doing something wrong there but wasn't sure haha. Thanks!

**Review by fallaciousreasoning — APPROVED** [review]
Still LGTM

**Pull request merged**
