### PR TITLE
[Variables]: Update from Figma

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Update variables from Figma using https://github.com/fallaciousreasoning/figma-exporter

### CODE REVIEW

**Review by AlanBreck — APPROVED** [review]

**Comment by AlanBreck** [comment]
For some reason, my token stories aren't picking up on the `-1` colors. 🤔

**Comment by fallaciousreasoning** [comment]
That's weird @AlanBreck! I just had a look through the stories and all the components still look good. I think we can merge but I'll let @petemill take a glance too

**Review by petemill — APPROVED** [review]
weird github diff, but looks ok!

**Comment by fallaciousreasoning** [comment]
I know right - it's so confusing to read :laughing: Okay, I'm going to land this

**Pull request merged**
