### PR TITLE
menu has user controlled height now

### PR DESCRIPTION
**Pull request by nullhook**

### CODE REVIEW

**Comment by AlanBreck** [comment]
@nullhook, we've been somewhat careful to limit how many options we expose on each component. Can you explain more about why this is necessary?

**Comment by nullhook** [comment]
image

i'm implementing a feature in aichat called 'slash tools' that anchors a button menu to the input box, allowing users to select an action. since the list can be lengthy, we plan to limit the maximum height of the button menu to prevent it from covering the chat conversation.

**Review by fallaciousreasoning — APPROVED** [review]
No objections on my end.

**Review by AlanBreck — APPROVED** [review]
LGTM as well.

@nullhook, when you `Squash and merge`, would you please format the commit message to the following?

```
[Component]: description of change starting with imperative verb
```

For instance it could be:

```
[ButtonMenu]: adds public css variable for setting max height
```

...or something along those lines.

**Pull request merged**
