### PR TITLE
Separate Button into a separate Link and Button component to fix typings.

### PR DESCRIPTION
**Pull request by fallaciousreasoning**

### CODE REVIEW

**Comment by AlanBreck** [comment]
No!! :-(

Not happy with Svelte right now.

**Comment by fallaciousreasoning** [comment]
I can get the typings working for the `anchor`/`button` component but then it breaks the React wrapper :D I can have a bit more of a dig if you like?

**Comment by fallaciousreasoning** [comment]
Have a look at #136 and see if that looks better? Both ways aren't ideal, but hopefully the solution in #136 disappears into the background a bit more

**Comment by fallaciousreasoning** [comment]
Closing in favor of #136

**Pull request closed without merging**
