### PR TITLE
bumps figma-api-exporter

### PR DESCRIPTION
**Pull request by AlanBreck**

### CODE REVIEW

**Review by fallaciousreasoning — APPROVED** [review]
LGTM, thanks @AlanBreck

**Comment by fallaciousreasoning** [comment]
@SocketSecurity ignore core-js@3.27.2
@SocketSecurity ignore core-js-pure@3.23.2

As per https://github.com/brave/brave-core/pull/17082#issuecomment-1424856642 this is safe to ignore the core-js `prepare` scripts.

I think the jest thing is probably fine too, but I'm not sure.

**Comment by AlanBreck** [comment]
cc @thypon

**Comment by AlanBreck** [comment]
@SocketSecurity ignore jest-cli@29.4.2

**Review by fallaciousreasoning — APPROVED** [review]
Still LGTM

**Pull request merged**
