### PR TITLE
[Tokens]: Update

### PR DESCRIPTION
**Pull request by aguscruiz**

### CODE REVIEW

**Review by fallaciousreasoning — APPROVED** [review]
LGTM

**Comment by AlanBreck** [comment]
Looks like our commit previews are broken. @brave/devops-team, any ideas?

**Review by AlanBreck — APPROVED** [review]
LGTM!

I'll need to update the Tailwind tokens to better accommodate the font styles, but I don't think that should block this PR.

**Comment by fallaciousreasoning** [comment]
cc @petemill I'd like to get your eyes on this before we land it.

**Review by petemill — APPROVED** [review]
This should be fun to update in the consuming projects!

**Comment by fallaciousreasoning** [comment]
Hey, so I think this is ready to land, but I really want https://github.com/brave/brave-core/pull/21005 to land first (as bumping this one is going to require some changes).

**Comment by aguscruiz** [comment]
> Hey, so I think this is ready to land, but I really want [brave/brave-core#21005](https://github.com/brave/brave-core/pull/21005) to land first (as bumping this one is going to require some changes).

OH ok no problem! We can update later

**Comment by fallaciousreasoning** [comment]
Yeah sorry @aguscruiz - this ones taking a long time to merge.

**Comment by fallaciousreasoning** [comment]
Going to land this now, as we've updated Brave Core to use Svelte 4!

**Pull request merged**
