### PR TITLE
[Icons]: Update icons from Figma

### PR DESCRIPTION
**Pull request by brave-support-admin**
> @brave/leo@0.0.1 update-icons
> node ./src/scripts/update-icons.js

Ignoring icon rainbow-color.svg because:
- has a raster image element
Ignoring icon bitcoin.com-color.svg because:
- has a raster image element
Ignoring icon daum-color.svg because:
- has a raster image element

### CODE REVIEW

**Comment by AlanBreck** [comment]
@aguscruiz, the changes to the icon colors seem pretty significant. Should these proceed to production, or do we need to wait to land this until we have corresponding color token updates?

**Comment by aguscruiz** [comment]
@AlanBreck safe to ignore, it's all because of the new tokens, they changed the icon's default color so that's why it's prompting it

**Comment by fallaciousreasoning** [comment]
@AlanBreck maybe we should always set the color on the icons to whatever value we have for `--leo-color-icon-default` or something, so that color changes in Figma don't trigger icon changes?

**Comment by AlanBreck** [comment]
> @AlanBreck maybe we should always set the color on the icons to whatever value we have for `--leo-color-icon-default` or something, so that color changes in Figma don't trigger icon changes?

@fallaciousreasoning, are you saying we could do that within our action/script for pulling icon changes?

**Pull request closed without merging**
