### PR TITLE
[Icons]: Update icons from Figma

### PR DESCRIPTION
**Pull request by brave-support-admin**
> @brave/leo@0.0.1 update-icons
> tsx ./src/scripts/update-icons.ts

Ignoring icon rainbow-color.svg because:
- has a raster image element
Ignoring icon bitcoin.com-color.svg because:
- has a raster image element
Ignoring icon daum-color.svg because:
- has a raster image element

### CODE REVIEW

**Review by AlanBreck — COMMENTED** [review]
@aguscruiz, did anything actually change here?

**Comment by aguscruiz** [comment]
@AlanBreck I don't think so, I only have changes in the variables file

**Comment by AlanBreck** [comment]
Hmmmm... @fallaciousreasoning, any idea why this PR was triggered in the first place?

**Comment by fallaciousreasoning** [comment]
Look like all the stroke colors have changed :/

**Comment by aguscruiz** [comment]
Ohhh I see, it's because I changed the divider/subtle variable because of this issue I was telling you about the mapping. All the payment icons used that one so they just got updated. It's just a stroke color change like Jay said

**Review by AlanBreck — APPROVED** [review]

**Pull request merged**
